### ISSUE TITLE
Gameplay: Same Letter Penalty

### ISSUE THREAD

**Issue by dbdoyle182** [chaseeffler/WordGame#1]
The user loses a guess every time something is clicked, even if I guess the same letter multiple times. Think about how you could use a if/else statement to check and see if the letter has been guessed already, and if it has, display a message letting the user know they've already guessed that letter, if it hasn't been guessed yet then give them the penalty.

**Comment by chaseeffler** [comment]
In my opinion, if the user guesses the same letter multiple times, they're dumb and deserve to lose a guess
